package com.myspace.expensescms;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Expense implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "EXPENSE_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "EXPENSE_ID_SEQ", name = "EXPENSE_ID_GENERATOR")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label(value = "Employee")
	private java.lang.String employee;

	@org.kie.api.definition.type.Label(value = "Location")
	private java.lang.String location;

	@org.kie.api.definition.type.Label(value = "Department")
	private java.lang.String department;

	@org.kie.api.definition.type.Label(value = "Subject")
	private java.lang.String subject;

	@org.kie.api.definition.type.Label(value = "Amount")
	private java.lang.Double amount;

	@org.kie.api.definition.type.Label(value = "Approved")
	private java.lang.Boolean approved = false;

	public Expense() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getEmployee() {
		return this.employee;
	}

	public void setEmployee(java.lang.String employee) {
		this.employee = employee;
	}

	public java.lang.String getLocation() {
		return this.location;
	}

	public void setLocation(java.lang.String location) {
		this.location = location;
	}

	public java.lang.String getDepartment() {
		return this.department;
	}

	public void setDepartment(java.lang.String department) {
		this.department = department;
	}

	public java.lang.String getSubject() {
		return this.subject;
	}

	public void setSubject(java.lang.String subject) {
		this.subject = subject;
	}

	public java.lang.Double getAmount() {
		return this.amount;
	}

	public void setAmount(java.lang.Double amount) {
		this.amount = amount;
	}

	public java.lang.Boolean getApproved() {
		return this.approved;
	}

	public void setApproved(java.lang.Boolean approved) {
		this.approved = approved;
	}

	public Expense(java.lang.Long id, java.lang.String employee,
			java.lang.String location, java.lang.String department,
			java.lang.String subject, java.lang.Double amount,
			java.lang.Boolean approved) {
		this.id = id;
		this.employee = employee;
		this.location = location;
		this.department = department;
		this.subject = subject;
		this.amount = amount;
		this.approved = approved;
	}

}